09.01-Apul-mRNA-miRNA-interactions-CDS_5UTR
================
Kathleen Durkin
2025-06-18

- <a href="#1-mrna-coding-sequence" id="toc-1-mrna-coding-sequence">1 mRNA
  coding sequence</a>
  - <a href="#11-get-mature-mirna-fasta"
    id="toc-11-get-mature-mirna-fasta">1.1 Get mature miRNA fasta</a>
  - <a href="#12-get-coding-sequence-fasta"
    id="toc-12-get-coding-sequence-fasta">1.2 Get coding sequence fasta</a>
  - <a href="#13-run-miranda" id="toc-13-run-miranda">1.3 Run miRanda</a>
  - <a href="#14-summarize-results" id="toc-14-summarize-results">1.4
    Summarize results</a>
- <a href="#2-mirna-and-mrna-5utrs" id="toc-2-mirna-and-mrna-5utrs">2
  miRNA and mRNA 5’UTRs</a>
  - <a href="#21-get-5utr-fasta" id="toc-21-get-5utr-fasta">2.1 Get 5’UTR
    fasta</a>
  - <a href="#22-run-miranda" id="toc-22-run-miranda">2.2 Run miRanda</a>
  - <a href="#23-summarize-results" id="toc-23-summarize-results">2.3
    Summarize results</a>
- <a href="#3-mirna-and-mrna-3utrs" id="toc-3-mirna-and-mrna-3utrs">3
  miRNA and mRNA 3’UTRs</a>
- <a href="#4-summary" id="toc-4-summary">4 Summary</a>
- <a href="#5-combine-with-pcc" id="toc-5-combine-with-pcc">5 Combine with
  PCC</a>
  - <a href="#51-merge-with-cds-miranda-results"
    id="toc-51-merge-with-cds-miranda-results">5.1 Merge with CDS miRanda
    results</a>
  - <a href="#52-merge-with-5utr-miranda-results"
    id="toc-52-merge-with-5utr-miranda-results">5.2 Merge with 5UTR miRanda
    results</a>

miRanda is a target prediction software, used to identify likely
miRNA-mRNA interactions.

We’ve decided that we need to expand our consideration of potential
miRNA target sites to include the coding sequence and (potentially) the
5’UTR region, since cnidarian miRNAs may function primarily through
target cleavage, instead of translational repression.

Run miRanda using the mRNA coding sequences and the 1kb 5UTR regions as
inputs.

``` r
library(dplyr)
```

    ## 
    ## Attaching package: 'dplyr'

    ## The following objects are masked from 'package:stats':
    ## 
    ##     filter, lag

    ## The following objects are masked from 'package:base':
    ## 
    ##     intersect, setdiff, setequal, union

# 1 mRNA coding sequence

## 1.1 Get mature miRNA fasta

``` bash
awk '/^>/ {keep = ($0 ~ /mature/)} keep' ../output/11-Apul-sRNA-ShortStack_4.1.0-pulchra_genome/ShortStack_out/mir.fasta > ../output/09.01-Apul-mRNA-miRNA-interactions-CDS_5UTR/Apul_ShortStack_4.1.0_mature.fasta
```

## 1.2 Get coding sequence fasta

``` bash

/home/shared/bedtools2/bin/bedtools getfasta \
-fi "../data/Apulchra-genome.fa" \
-bed "../output/15-Apul-annotate-UTRs/Apulcra-genome-mRNA_only.gff" \
-fo "../output/09.01-Apul-mRNA-miRNA-interactions-CDS_5UTR/Apul_mRNA_full.fa"
```

## 1.3 Run miRanda

``` bash

# score cutoff >100
# energy cutoff <-20
# strict binding

/home/shared/miRanda-3.3a/src/miranda \
../output/09.01-Apul-mRNA-miRNA-interactions-CDS_5UTR/Apul_ShortStack_4.1.0_mature.fasta \
../output/09.01-Apul-mRNA-miRNA-interactions-CDS_5UTR/Apul_mRNA_full.fa \
-sc 100 \
-en -20 \
-strict \
-out ../output/09.01-Apul-mRNA-miRNA-interactions-CDS_5UTR/Apul-miRanda-mRNA_full-strict_all.tab
```

## 1.4 Summarize results

Let’s look at the output

``` bash

echo "miranda run finished!"
echo "counting number of putative interactions predicted"

zgrep -c "Performing Scan" ../output/09.01-Apul-mRNA-miRNA-interactions-CDS_5UTR/Apul-miRanda-mRNA_full-strict_all.tab

echo "Parsing output"
grep -A 1 "Scores for this hit:" ../output/09.01-Apul-mRNA-miRNA-interactions-CDS_5UTR/Apul-miRanda-mRNA_full-strict_all.tab | sort | grep '>' > ../output/09.01-Apul-mRNA-miRNA-interactions-CDS_5UTR/Apul-miRanda-mRNA_full-strict-parsed.txt

echo "counting number of putative interactions predicted"
wc -l ../output/09.01-Apul-mRNA-miRNA-interactions-CDS_5UTR/Apul-miRanda-mRNA_full-strict-parsed.txt
```

    ## miranda run finished!
    ## counting number of putative interactions predicted
    ## 1421433
    ## Parsing output
    ## counting number of putative interactions predicted
    ## 38152 ../output/09.01-Apul-mRNA-miRNA-interactions-CDS_5UTR/Apul-miRanda-mRNA_full-strict-parsed.txt

This is a lot of putative interactions! Note though, that miRanda only
requires complementarity of a 8bp seed region of the miRNA. We instead
want to look for binding with full or near-full complementarity. Let’s
look at how many putative interactions are predicted for a binding
length of at least 21 nucleotides (the length of our smallest mature
miRNA).

``` bash
echo "number of putative interactions of at least 21 nucleotides"
awk -F'\t' '$7 >= 21' ../output/09.01-Apul-mRNA-miRNA-interactions-CDS_5UTR/Apul-miRanda-mRNA_full-strict-parsed.txt | wc -l
echo ""
echo "check some:"
awk -F'\t' '$7 >= 21' ../output/09.01-Apul-mRNA-miRNA-interactions-CDS_5UTR/Apul-miRanda-mRNA_full-strict-parsed.txt | head -5
```

    ## number of putative interactions of at least 21 nucleotides
    ## 11282
    ## 
    ## check some:
    ## >Cluster_10051.mature::ptg000016l:7795530-7795551(+) ntLink_6:10104556-10114024  155.00  -21.12  2 21    8084 8107   21  66.67%  76.19%
    ## >Cluster_10051.mature::ptg000016l:7795530-7795551(+) ntLink_6:10392093-10402892  157.00  -20.28  2 21    4608 4632   22  77.27%  77.27%
    ## >Cluster_10051.mature::ptg000016l:7795530-7795551(+) ntLink_6:11414771-11436218  163.00  -20.28  2 21    3703 3727   22  72.73%  77.27%
    ## >Cluster_10051.mature::ptg000016l:7795530-7795551(+) ntLink_6:18205280-18224347  150.00  -21.35  2 21    9845 9872   25  64.00%  72.00%
    ## >Cluster_10051.mature::ptg000016l:7795530-7795551(+) ntLink_6:6386002-6398066    150.00  -21.10  2 21    10772 10796 22  63.64%  77.27%

We can also see from the percent identities (last 2 entries) that this
number includes alignments with multiple mismatches. Let’s filter again
to reduce the number of permissible mismatches. Let’s say we want no
more than 3 mismatches. For an alignment of 21 nucleotides, this would
be an alignment rate of (21-3)/21 = 85.7%.

``` bash
echo "number of putative interactions of at least 21 nucleotides, with at most 3 mismatches"
awk -F'\t' '$7 >= 21' ../output/09.01-Apul-mRNA-miRNA-interactions-CDS_5UTR/Apul-miRanda-mRNA_full-strict-parsed.txt | awk -F'\t' '$8 >= 85' | wc -l
echo ""
echo "check some:"
awk -F'\t' '$7 >= 21' ../output/09.01-Apul-mRNA-miRNA-interactions-CDS_5UTR/Apul-miRanda-mRNA_full-strict-parsed.txt | awk -F'\t' '$8 >= 85' | head -5
```

    ## number of putative interactions of at least 21 nucleotides, with at most 3 mismatches
    ## 107
    ## 
    ## check some:
    ## >Cluster_10057.mature::ptg000016l:8599884-8599905(-) ptg000017l:7171736-7192592  174.00  -21.36  2 21    13035 13058 21  85.71%  85.71%
    ## >Cluster_10093.mature::ptg000016l:11751407-11751428(-)   ptg000007l:5326404-5332924  179.00  -25.97  2 21    658 681 21  85.71%  85.71%
    ## >Cluster_10228.mature::ptg000017l:7471168-7471190(+) ntLink_8:9921794-9928534    179.00  -26.55  2 22    872 896 22  86.36%  86.36%
    ## >Cluster_10228.mature::ptg000017l:7471168-7471190(+) ptg000019l:1503591-1507594  188.00  -31.70  2 22    3554 3577   21  85.71%  95.24%
    ## >Cluster_10228.mature::ptg000017l:7471168-7471190(+) ptg000039l:790628-797014    188.00  -25.92  2 22    5693 5716   21  90.48%  90.48%

So filtering for full or near-full complementarity reduced the number of
putative interactions between miRNA and full mRNA sequences from 38152
to 107.

# 2 miRNA and mRNA 5’UTRs

We’ve also created a gff of 1kb 5’UTR regions (using the same method
used to define 1kb 3’UTRs, in `05-Apul-annotate-UTRs`). Let’s try
running this through miRanda as well, since it’s possible (though not
necessarily expected) that miRNAs will bind here

## 2.1 Get 5’UTR fasta

``` bash
/home/shared/bedtools2/bin/bedtools getfasta \
-fi "../data/Apulchra-genome.fa" \
-bed "../output/05-Apul-annotate-UTRs/Apul.GFFannotation.5UTR_1kb_corrected.gff" \
-fo "../output/09.01-Apul-mRNA-miRNA-interactions-CDS_5UTR/Apul_5UTR_1kb_corrected.fa"
```

## 2.2 Run miRanda

``` bash

# Same settings we've been using: 
# score cutoff >100
# energy cutoff <-10
# strict binding

/home/shared/miRanda-3.3a/src/miranda \
../data/06-Apul-miRNA-mRNA-RNAhybrid/miRNA_mature-Apul.fasta \
../output/09.01-Apul-mRNA-miRNA-interactions-CDS_5UTR/Apul_5UTR_1kb_corrected.fa \
-sc 100 \
-en -10 \
-strict \
-out ../output/09.01-Apul-mRNA-miRNA-interactions-CDS_5UTR/Apul-miRanda-5UTR_1kb-strict_all.tab
```

## 2.3 Summarize results

Let’s look at the output

``` bash

echo "Number of interacting miRNA-5UTR pairs"
zgrep -c "Performing Scan" ../output/09.01-Apul-mRNA-miRNA-interactions-CDS_5UTR/Apul-miRanda-5UTR_1kb-strict_all.tab

echo "Parsing output"
grep -A 1 "Scores for this hit:" ../output/09.01-Apul-mRNA-miRNA-interactions-CDS_5UTR/Apul-miRanda-5UTR_1kb-strict_all.tab | sort | grep '>' > ../output/09.01-Apul-mRNA-miRNA-interactions-CDS_5UTR/Apul-miRanda-5UTR_1kb-strict-parsed.txt

echo "Number of putative interactions predicted"
wc -l ../output/09.01-Apul-mRNA-miRNA-interactions-CDS_5UTR/Apul-miRanda-5UTR_1kb-strict-parsed.txt
```

    ## Number of interacting miRNA-5UTR pairs
    ## 1449162
    ## Parsing output
    ## Number of putative interactions predicted
    ## 4959 ../output/09.01-Apul-mRNA-miRNA-interactions-CDS_5UTR/Apul-miRanda-5UTR_1kb-strict-parsed.txt

How many putative interactions are predicted for a binding length of at
least 21 nucleotides (the length of our smallest mature miRNA)?

``` bash
echo "number of putative interactions:"
wc -l ../output/09.01-Apul-mRNA-miRNA-interactions-CDS_5UTR/Apul-miRanda-5UTR_1kb-strict-parsed.txt
echo ""
echo "number of putative interactions of at least 21 nucleotides"
awk -F'\t' '$7 >= 21' ../output/09.01-Apul-mRNA-miRNA-interactions-CDS_5UTR/Apul-miRanda-5UTR_1kb-strict-parsed.txt | wc -l
echo ""
echo "number of putative interactions of at least 21 nucleotides, with at most 3 mismatches"
awk -F'\t' '$7 >= 21' ../output/09.01-Apul-mRNA-miRNA-interactions-CDS_5UTR/Apul-miRanda-5UTR_1kb-strict-parsed.txt | awk -F'\t' '$8 >= 85' | wc -l
```

    ## number of putative interactions:
    ## 4959 ../output/09.01-Apul-mRNA-miRNA-interactions-CDS_5UTR/Apul-miRanda-5UTR_1kb-strict-parsed.txt
    ## 
    ## number of putative interactions of at least 21 nucleotides
    ## 1421
    ## 
    ## number of putative interactions of at least 21 nucleotides, with at most 3 mismatches
    ## 11

So filtering for full or near-full complementarity reduced the number of
putative interactions between miRNA and 5’UTR sequences from 4959 to 11

# 3 miRNA and mRNA 3’UTRs

Now let’s see how filtering changes the outputs of miRanda run with only
the 3’UTR mRNA region (the input we have been using up till now)

``` bash
echo "total number of putative interactions:"
wc -l ../output/09-Apul-mRNA-miRNA-interactions/miranda_strict_all_1kb_parsed_apul_updated.txt

echo "number of putative interactions of at least 21 nucleotides"
awk -F'\t' '$7 >= 21' ../output/09-Apul-mRNA-miRNA-interactions/miranda_strict_all_1kb_parsed_apul_updated.txt | wc -l

echo "number of putative interactions of at least 21 nucleotides, with at most 3 mismatches"
awk -F'\t' '$7 >= 21' ../output/09-Apul-mRNA-miRNA-interactions/miranda_strict_all_1kb_parsed_apul_updated.txt | awk -F'\t' '$8 >= 85' | wc -l
```

    ## total number of putative interactions:
    ## 6109 ../output/09-Apul-mRNA-miRNA-interactions/miranda_strict_all_1kb_parsed_apul_updated.txt
    ## number of putative interactions of at least 21 nucleotides
    ## 1699
    ## number of putative interactions of at least 21 nucleotides, with at most 3 mismatches
    ## 13

When only mRNA 3’UTR regions are used as input, filtering for
full/near-full complementarity reduces the number of putative
interactions from 6109 to 13.

# 4 Summary

| Input     | unfiltered | filtered for complementarity | % retained |
|:----------|:-----------|:-----------------------------|:-----------|
| full mRNA | 38152      | 107                          | 0.280 %    |
| 5’UTR     | 4959       | 11                           | 0.222 %    |
| 3’UTR     | 6109       | 13                           | 0.213 %    |

# 5 Combine with PCC

We’ve also already calculated pairwise Pearson’s correlation
coefficients for every miRNA-mRNA pair. Let’s merge this table with our
CDS and 5UTR miRanda results to see which instances of putative binding
are supported through expression correlation.

PCC table available at
`https://gannet.fish.washington.edu/kdurkin1/ravenbackups/deep-dive-expression/D-Apul/output/09-Apul-mRNA-miRNA-interactions/Apul-PCC_miRNA_mRNA.csv`
(too large to store on Gannet), originally generated in
`D-Apul/code/09-Apul-mRNA-miRNA-interactions.Rmd`

## 5.1 Merge with CDS miRanda results

Read in PCC and miRanda tables

``` r
# Load
Apul_PCC_miRNA_mRNA <- read.csv("https://gannet.fish.washington.edu/kdurkin1/ravenbackups/deep-dive-expression/D-Apul/output/09-Apul-mRNA-miRNA-interactions/Apul-PCC_miRNA_mRNA.csv") %>% select(-X)
Apul_miRanda_miRNA_CDS <- read.table("../output/09.01-Apul-mRNA-miRNA-interactions-CDS_5UTR/Apul-miRanda-mRNA_full-strict-parsed.txt")

# Format the miRNA IDs in miRanda table by removing miRNA coordinates
Apul_miRanda_miRNA_CDS$V1 <- gsub(">", "", Apul_miRanda_miRNA_CDS$V1)
Apul_miRanda_miRNA_CDS$V1 <- sub("\\..*", "", Apul_miRanda_miRNA_CDS$V1)
```

We need to associate the CDS genomic coordinates (used in miRanda
output) with gene IDs (used in PCC output)

``` r
# Load and format mapping table
Apul_mRNA_FUNids <- read.table("../output/15-Apul-annotate-UTRs/Apul-mRNA-FUNids.txt") %>% select(V1, V4)
Apul_mRNA_FUNids$V4 <- gsub("Parent=", "", Apul_mRNA_FUNids$V4)

# Join with miRanda table to annotate genomic coordinates with gene IDs
Apul_miRanda_miRNA_CDS <- left_join(Apul_miRanda_miRNA_CDS, Apul_mRNA_FUNids, by = c("V2" = "V1")) %>% unique()
```

Great! Now we can merge the CDS miRanda results and PCC values

``` r
# Merge
Apul_miRanda_miRNA_CDS_PCC <- left_join(Apul_miRanda_miRNA_CDS, Apul_PCC_miRNA_mRNA, by = c("V1" = "miRNA", "V4.y" = "mRNA")) %>% unique()

# Save
write.csv(Apul_miRanda_miRNA_CDS_PCC, "../output/09.01-Apul-mRNA-miRNA-interactions-CDS_5UTR/miRanda_PCC_miRNA_CDS.csv")
```

Note: there may be some NA values in the PCC columns. This would
indicate that one (or both) of the member of that miRNA-mRNA pair had
all-zero counts (i.e. it was unexpressed in all samples)

## 5.2 Merge with 5UTR miRanda results

Read in PCC and miRanda tables

``` r
# Load
Apul_PCC_miRNA_mRNA <- read.csv("https://gannet.fish.washington.edu/kdurkin1/ravenbackups/deep-dive-expression/D-Apul/output/09-Apul-mRNA-miRNA-interactions/Apul-PCC_miRNA_mRNA.csv") %>% select(-X)
Apul_miRanda_miRNA_5UTR <- read.table("../output/09.01-Apul-mRNA-miRNA-interactions-CDS_5UTR/Apul-miRanda-5UTR_1kb-strict-parsed.txt")

# Format the miRNA IDs in miRanda table by removing miRNA coordinates
Apul_miRanda_miRNA_5UTR$V1 <- gsub(">", "", Apul_miRanda_miRNA_5UTR$V1)
Apul_miRanda_miRNA_5UTR$V1 <- sub("\\..*", "", Apul_miRanda_miRNA_5UTR$V1)
```

We need to associate the 5UTR genomic coordinates (used in miRanda
output) with gene IDs (used in PCC output)

``` r
# Load and format mapping table
Apul_5UTR_FUNids <- read.table("../output/15-Apul-annotate-UTRs/Apul-5UTR-FUNids.txt") %>% select(V1, V4)
Apul_5UTR_FUNids$V4 <- gsub("Parent=", "", Apul_5UTR_FUNids$V4)

# Join with miRanda table to annotate genomic coordinates with gene IDs
Apul_miRanda_miRNA_5UTR <- left_join(Apul_miRanda_miRNA_5UTR, Apul_5UTR_FUNids, by = c("V2" = "V1")) %>% unique()
```

    ## Warning in left_join(Apul_miRanda_miRNA_5UTR, Apul_5UTR_FUNids, by = c(V2 = "V1")): Detected an unexpected many-to-many relationship between `x` and `y`.
    ## ℹ Row 12 of `x` matches multiple rows in `y`.
    ## ℹ Row 7115 of `y` matches multiple rows in `x`.
    ## ℹ If a many-to-many relationship is expected, set `relationship =
    ##   "many-to-many"` to silence this warning.

Great! Now we can merge the 5UTR miRanda results and PCC values

``` r
# Merge
Apul_miRanda_miRNA_5UTR_PCC <- left_join(Apul_miRanda_miRNA_5UTR, Apul_PCC_miRNA_mRNA, by = c("V1" = "miRNA", "V4.y" = "mRNA")) %>% unique()

# Save
write.csv(Apul_miRanda_miRNA_5UTR_PCC, "../output/09.01-Apul-mRNA-miRNA-interactions-CDS_5UTR/miRanda_PCC_miRNA_5UTR.csv")
```

Note: there may be some NA values in the PCC columns. This would
indicate that one (or both) of the member of that miRNA-mRNA pair had
all-zero counts (i.e. it was unexpressed in all samples)
