11.01-Ptuh-mRNA-miRNA-interactions-CDS_5UTR
================
Kathleen Durkin
2024-02-21

- <a href="#1-mrna-coding-sequence" id="toc-1-mrna-coding-sequence">1 mRNA
  coding sequence</a>
  - <a href="#11-get-mature-mirna-fasta"
    id="toc-11-get-mature-mirna-fasta">1.1 Get mature miRNA fasta</a>
  - <a href="#12-get-coding-sequence-fasta"
    id="toc-12-get-coding-sequence-fasta">1.2 Get coding sequence fasta</a>
  - <a href="#13-run-miranda" id="toc-13-run-miranda">1.3 Run miRanda</a>
  - <a href="#14-summarize-results" id="toc-14-summarize-results">1.4
    Summarize results</a>
- <a href="#2-mirna-and-mrna-5utrs" id="toc-2-mirna-and-mrna-5utrs">2
  miRNA and mRNA 5’UTRs</a>
  - <a href="#21-get-5utr-fasta" id="toc-21-get-5utr-fasta">2.1 Get 5’UTR
    fasta</a>
  - <a href="#22-run-miranda" id="toc-22-run-miranda">2.2 Run miRanda</a>
  - <a href="#23-summarize-results" id="toc-23-summarize-results">2.3
    Summarize results</a>
- <a href="#3-mirna-and-mrna-3utrs" id="toc-3-mirna-and-mrna-3utrs">3
  miRNA and mRNA 3’UTRs</a>
- <a href="#4-summary" id="toc-4-summary">4 Summary</a>
- <a href="#5-combine-with-pcc" id="toc-5-combine-with-pcc">5 Combine with
  PCC</a>
  - <a href="#51-merge-with-cds-miranda-results"
    id="toc-51-merge-with-cds-miranda-results">5.1 Merge with CDS miRanda
    results</a>
  - <a href="#52-merge-with-5utr-miranda-results"
    id="toc-52-merge-with-5utr-miranda-results">5.2 Merge with 5UTR miRanda
    results</a>

``` r
library(dplyr)
```

    ## 
    ## Attaching package: 'dplyr'

    ## The following objects are masked from 'package:stats':
    ## 
    ##     filter, lag

    ## The following objects are masked from 'package:base':
    ## 
    ##     intersect, setdiff, setequal, union

miRanda is a target prediction software, used to identify likely
miRNA-mRNA interactions.

We’ve decided that we need to expand our consideration of potential
miRNA target sites to include the coding sequence and (potentially) the
5’UTR region, since cnidarian miRNAs may function primarily through
target cleavage, instead of translational repression.

Run miRanda using the mRNA coding sequences and the 1kb 5UTR regions as
inputs.

# 1 mRNA coding sequence

## 1.1 Get mature miRNA fasta

``` bash
awk '/^>/ {keep = ($0 ~ /mature/)} keep' ../output/05-Ptuh-sRNA-ShortStack_4.1.0/ShortStack_out/mir.fasta > ../output/11.01-Ptuh-mRNA-miRNA-interactions-CDS_5UTR/Ptuh_ShortStack_4.1.0_mature.fasta
```

## 1.2 Get coding sequence fasta

``` bash

/home/shared/bedtools2/bin/bedtools getfasta \
-fi "../data/Pocillopora_meandrina_HIv1.assembly.fa" \
-bed "../output/16-Ptuh-annotate-UTRs/Ptuh-genome-mRNA_only.gff" \
-fo "../output/11.01-Ptuh-mRNA-miRNA-interactions-CDS_5UTR/Ptuh_mRNA_full.fa"
```

## 1.3 Run miRanda

``` bash

# score cutoff >100
# energy cutoff <-20
# strict binding

/home/shared/miRanda-3.3a/src/miranda \
../output/11.01-Ptuh-mRNA-miRNA-interactions-CDS_5UTR/Ptuh_ShortStack_4.1.0_mature.fasta \
../output/11.01-Ptuh-mRNA-miRNA-interactions-CDS_5UTR/Ptuh_mRNA_full.fa \
-sc 100 \
-en -20 \
-strict \
-out ../output/11.01-Ptuh-mRNA-miRNA-interactions-CDS_5UTR/Ptuh-miRanda-mRNA_full-strict_all.tab
```

## 1.4 Summarize results

Let’s look at the output

``` bash

echo "miranda run finished!"
echo "counting number of putative interactions predicted"

zgrep -c "Performing Scan" ../output/11.01-Ptuh-mRNA-miRNA-interactions-CDS_5UTR/Ptuh-miRanda-mRNA_full-strict_all.tab

echo "Parsing output"
grep -A 1 "Scores for this hit:" ../output/11.01-Ptuh-mRNA-miRNA-interactions-CDS_5UTR/Ptuh-miRanda-mRNA_full-strict_all.tab | sort | grep '>' > ../output/11.01-Ptuh-mRNA-miRNA-interactions-CDS_5UTR/Ptuh-miRanda-mRNA_full-strict-parsed.txt

echo "counting number of putative interactions predicted"
wc -l ../output/11.01-Ptuh-mRNA-miRNA-interactions-CDS_5UTR/Ptuh-miRanda-mRNA_full-strict-parsed.txt
```

    ## miranda run finished!
    ## counting number of putative interactions predicted
    ## 444155
    ## Parsing output
    ## counting number of putative interactions predicted
    ## 9537 ../output/11.01-Ptuh-mRNA-miRNA-interactions-CDS_5UTR/Ptuh-miRanda-mRNA_full-strict-parsed.txt

This is a lot of putative interactions! Note though, that miRanda only
requires complementarity of a 8bp seed region of the miRNA. We instead
want to look for binding with full or near-full complementarity. Let’s
look at how many putative interactions are predicted for a binding
length of at least 21 nucleotides (the length of our smallest mature
miRNA).

``` bash
echo "number of putative interactions of at least 21 nucleotides"
awk -F'\t' '$7 >= 21' ../output/11.01-Ptuh-mRNA-miRNA-interactions-CDS_5UTR/Ptuh-miRanda-mRNA_full-strict-parsed.txt | wc -l
echo ""
echo "check some:"
awk -F'\t' '$7 >= 21' ../output/11.01-Ptuh-mRNA-miRNA-interactions-CDS_5UTR/Ptuh-miRanda-mRNA_full-strict-parsed.txt | head -5
```

    ## number of putative interactions of at least 21 nucleotides
    ## 2384
    ## 
    ## check some:
    ## >Cluster_1015.mature::Pocillopora_meandrina_HIv1___Sc0000002:10845744-10845765(-)    Pocillopora_meandrina_HIv1___Sc0000000:12883388-12902201    149.00  -20.34  2 21    10641 10667 24  70.83%  70.83%
    ## >Cluster_1015.mature::Pocillopora_meandrina_HIv1___Sc0000002:10845744-10845765(-)    Pocillopora_meandrina_HIv1___Sc0000000:13480158-13493628    145.00  -21.67  2 20    13018 13042 21  61.90%  76.19%
    ## >Cluster_1015.mature::Pocillopora_meandrina_HIv1___Sc0000002:10845744-10845765(-)    Pocillopora_meandrina_HIv1___Sc0000000:13585121-13600931    145.00  -21.67  2 20    15372 15396 21  61.90%  76.19%
    ## >Cluster_1015.mature::Pocillopora_meandrina_HIv1___Sc0000002:10845744-10845765(-)    Pocillopora_meandrina_HIv1___Sc0000000:13688033-13707896    145.00  -21.67  2 20    19417 19441 21  61.90%  76.19%
    ## >Cluster_1015.mature::Pocillopora_meandrina_HIv1___Sc0000002:10845744-10845765(-)    Pocillopora_meandrina_HIv1___Sc0000000:13822131-13825033    145.00  -21.67  2 20    2456 2480   21  61.90%  76.19%

We can also see from the percent identities (last 2 entries) that this
number includes alignments with multiple mismatches. Let’s filter again
to reduce the number of permissible mismatches. Let’s say we want no
more than 3 mismatches. For an alignment of 21 nucleotides, this would
be an alignment rate of (21-3)/21 = 85.7%.

``` bash
echo "number of putative interactions of at least 21 nucleotides, with at most 3 mismatches"
awk -F'\t' '$7 >= 21' ../output/11.01-Ptuh-mRNA-miRNA-interactions-CDS_5UTR/Ptuh-miRanda-mRNA_full-strict-parsed.txt | awk -F'\t' '$8 >= 85' | wc -l
echo ""
echo "check some:"
awk -F'\t' '$7 >= 21' ../output/11.01-Ptuh-mRNA-miRNA-interactions-CDS_5UTR/Ptuh-miRanda-mRNA_full-strict-parsed.txt | awk -F'\t' '$8 >= 85' | head -5
```

    ## number of putative interactions of at least 21 nucleotides, with at most 3 mismatches
    ## 27
    ## 
    ## check some:
    ## >Cluster_1116.mature::Pocillopora_meandrina_HIv1___Sc0000003:495117-495138(+)    Pocillopora_meandrina_HIv1___Sc0000002:19443263-19445494    183.00  -32.26  2 21    424 447 21  85.71%  90.48%
    ## >Cluster_1116.mature::Pocillopora_meandrina_HIv1___Sc0000003:495117-495138(+)    Pocillopora_meandrina_HIv1___Sc0000002:6370064-6388306  174.00  -23.39  2 21    15466 15489 21  85.71%  85.71%
    ## >Cluster_1116.mature::Pocillopora_meandrina_HIv1___Sc0000003:495117-495138(+)    Pocillopora_meandrina_HIv1___Sc0000029:1950754-1962391  174.00  -21.65  2 21    8886 8909   21  85.71%  85.71%
    ## >Cluster_1289.mature::Pocillopora_meandrina_HIv1___Sc0000003:10129534-10129556(-)    Pocillopora_meandrina_HIv1___Sc0000002:17926895-17936279    187.00  -27.52  2 22    9282 9306   22  90.91%  90.91%
    ## >Cluster_1289.mature::Pocillopora_meandrina_HIv1___Sc0000003:10129534-10129556(-)    Pocillopora_meandrina_HIv1___Sc0000004:3597097-3614311  174.00  -20.65  2 22    15654 15676 21  85.71%  85.71%

So filtering for full or near-full complementarity reduced the number of
putative interactions between miRNA and full mRNA sequences from 9537 to
27

# 2 miRNA and mRNA 5’UTRs

We’ve also created a gff of 1kb 5’UTR regions (using the same method
used to define 1kb 3’UTRs, in `16-Ptuh-annotate-UTRs`). Let’s try
running this through miRanda as well, since it’s possible (though not
necessarily expected) that miRNAs will bind here

## 2.1 Get 5’UTR fasta

``` bash
/home/shared/bedtools2/bin/bedtools getfasta \
-fi "../data/Pocillopora_meandrina_HIv1.assembly.fa" \
-bed "../output/16-Ptuh-annotate-UTRs/Ptuh.GFFannotation.5UTR_1kb_corrected.gff" \
-fo "../output/11.01-Ptuh-mRNA-miRNA-interactions-CDS_5UTR/Ptuh_5UTR_1kb_corrected.fa"
```

## 2.2 Run miRanda

``` bash

# Same settings we've been using: 
# score cutoff >100
# energy cutoff <-20
# strict binding

/home/shared/miRanda-3.3a/src/miranda \
../output/11.01-Ptuh-mRNA-miRNA-interactions-CDS_5UTR/Ptuh_ShortStack_4.1.0_mature.fasta \
../output/11.01-Ptuh-mRNA-miRNA-interactions-CDS_5UTR/Ptuh_5UTR_1kb_corrected.fa \
-sc 100 \
-en -20 \
-strict \
-out ../output/11.01-Ptuh-mRNA-miRNA-interactions-CDS_5UTR/Ptuh-miRanda-5UTR_1kb-strict_all.tab
```

## 2.3 Summarize results

Let’s look at the output

``` bash

echo "Number of interacting miRNA-lncRNA pairs"
zgrep -c "Performing Scan" ../output/11.01-Ptuh-mRNA-miRNA-interactions-CDS_5UTR/Ptuh-miRanda-5UTR_1kb-strict_all.tab

echo "Parsing output"
grep -A 1 "Scores for this hit:" ../output/11.01-Ptuh-mRNA-miRNA-interactions-CDS_5UTR/Ptuh-miRanda-5UTR_1kb-strict_all.tab | sort | grep '>' > ../output/11.01-Ptuh-mRNA-miRNA-interactions-CDS_5UTR/Ptuh-miRanda-5UTR_1kb-strict-parsed.txt

echo "Number of putative interactions predicted"
wc -l ../output/11.01-Ptuh-mRNA-miRNA-interactions-CDS_5UTR/Ptuh-miRanda-5UTR_1kb-strict-parsed.txt
```

    ## Number of interacting miRNA-lncRNA pairs
    ## 1207347
    ## Parsing output
    ## Number of putative interactions predicted
    ## 3881 ../output/11.01-Ptuh-mRNA-miRNA-interactions-CDS_5UTR/Ptuh-miRanda-5UTR_1kb-strict-parsed.txt

How many putative interactions are predicted for a binding length of at
least 21 nucleotides (the length of our smallest mature miRNA)?

``` bash
echo "number of putative interactions:"
wc -l ../output/11.01-Ptuh-mRNA-miRNA-interactions-CDS_5UTR/Ptuh-miRanda-5UTR_1kb-strict-parsed.txt
echo ""
echo "number of putative interactions of at least 21 nucleotides"
awk -F'\t' '$7 >= 21' ../output/11.01-Ptuh-mRNA-miRNA-interactions-CDS_5UTR/Ptuh-miRanda-5UTR_1kb-strict-parsed.txt | wc -l
echo ""
echo "number of putative interactions of at least 21 nucleotides, with at most 3 mismatches"
awk -F'\t' '$7 >= 21' ../output/11.01-Ptuh-mRNA-miRNA-interactions-CDS_5UTR/Ptuh-miRanda-5UTR_1kb-strict-parsed.txt | awk -F'\t' '$8 >= 85' | wc -l
```

    ## number of putative interactions:
    ## 3881 ../output/11.01-Ptuh-mRNA-miRNA-interactions-CDS_5UTR/Ptuh-miRanda-5UTR_1kb-strict-parsed.txt
    ## 
    ## number of putative interactions of at least 21 nucleotides
    ## 827
    ## 
    ## number of putative interactions of at least 21 nucleotides, with at most 3 mismatches
    ## 5

So filtering for full or near-full complementarity reduced the number of
putative interactions between miRNA and 5’UTR sequences from 3881 to 5

# 3 miRNA and mRNA 3’UTRs

Now let’s see how filtering changes the outputs of miRanda run with only
the 3’UTR mRNA region (the input we have been using up till now)

``` bash
echo "total number of putative interactions:"
wc -l ../output/11-Ptuh-mRNA-miRNA-interactions/three_prime_interaction/miranda_strict_all_1kb_parsed_ptuh_updated.txt

echo "number of putative interactions of at least 21 nucleotides"
awk -F'\t' '$7 >= 21' ../output/11-Ptuh-mRNA-miRNA-interactions/three_prime_interaction/miranda_strict_all_1kb_parsed_ptuh_updated.txt | wc -l

echo "number of putative interactions of at least 21 nucleotides, with at most 3 mismatches"
awk -F'\t' '$7 >= 21' ../output/11-Ptuh-mRNA-miRNA-interactions/three_prime_interaction/miranda_strict_all_1kb_parsed_ptuh_updated.txt | awk -F'\t' '$8 >= 85' | wc -l
```

    ## total number of putative interactions:
    ## 4105 ../output/11-Ptuh-mRNA-miRNA-interactions/three_prime_interaction/miranda_strict_all_1kb_parsed_ptuh_updated.txt
    ## number of putative interactions of at least 21 nucleotides
    ## 846
    ## number of putative interactions of at least 21 nucleotides, with at most 3 mismatches
    ## 11

When only mRNA 3’UTR regions are used as input, filtering for
full/near-full complementarity reduces the number of putative
interactions from 4105 to 11.

# 4 Summary

| Input     | unfiltered | filtered for complementarity | % retained |
|:----------|:-----------|:-----------------------------|:-----------|
| full mRNA | 9537       | 27                           | 0.283 %    |
| 5’UTR     | 3881       | 5                            | 0.129 %    |
| 3’UTR     | 4105       | 11                           | 0.268 %    |

# 5 Combine with PCC

We’ve also already calculated pairwise Pearson’s correlation
coefficients for every miRNA-mRNA pair. Let’s merge this table with our
CDS and 5UTR miRanda results to see which instances of putative binding
are supported through expression correlation.

PCC table available at
`https://gannet.fish.washington.edu/kdurkin1/ravenbackups/deep-dive-expression/F-Ptuh/output/11-Ptuh-mRNA-miRNA-interactions/three_prime_interaction/Ptuh-PCC_miRNA_mRNA.csv`
(too large to store on Github), originally generated in
`F-Ptuh/code/11-Ptuh-mRNA-miRNA-interactions.Rmd`

## 5.1 Merge with CDS miRanda results

Read in PCC and miRanda tables

``` r
# Load
Ptuh_PCC_miRNA_mRNA <- read.csv("https://gannet.fish.washington.edu/kdurkin1/ravenbackups/deep-dive-expression/F-Ptuh/output/11-Ptuh-mRNA-miRNA-interactions/three_prime_interaction/Ptuh-PCC_miRNA_mRNA.csv") %>% select(-X)
Ptuh_miRanda_miRNA_CDS <- read.table("../output/11.01-Ptuh-mRNA-miRNA-interactions-CDS_5UTR/Ptuh-miRanda-mRNA_full-strict-parsed.txt")

# Format the miRNA IDs in miRanda table by removing miRNA coordinates
Ptuh_miRanda_miRNA_CDS$V1 <- gsub(">", "", Ptuh_miRanda_miRNA_CDS$V1)
Ptuh_miRanda_miRNA_CDS$V1 <- sub("\\..*", "", Ptuh_miRanda_miRNA_CDS$V1)
```

We need to associate the CDS genomic coordinates (used in miRanda
output) with gene IDs (used in PCC output)

``` r
# Load and format mapping table
Ptuh_mRNA_FUNids <- read.table("../output/16-Ptuh-annotate-UTRs/Ptuh-mRNA-geneIDs.txt") %>% select(V1, V4)
Ptuh_mRNA_FUNids$V4 <- gsub("Parent=gene-", "", Ptuh_mRNA_FUNids$V4)

# Join with miRanda table to annotate genomic coordinates with gene IDs
Ptuh_miRanda_miRNA_CDS <- left_join(Ptuh_miRanda_miRNA_CDS, Ptuh_mRNA_FUNids, by = c("V2" = "V1")) %>% unique()
```

Great! Now we can merge the CDS miRanda results and PCC values

``` r
# Merge
Ptuh_miRanda_miRNA_CDS_PCC <- left_join(Ptuh_miRanda_miRNA_CDS, Ptuh_PCC_miRNA_mRNA, by = c("V1" = "miRNA", "V4.y" = "mRNA")) %>% unique()

# Save
write.csv(Ptuh_miRanda_miRNA_CDS_PCC, "../output/11.01-Ptuh-mRNA-miRNA-interactions-CDS_5UTR/miRanda_PCC_miRNA_CDS.csv")
```

Note: there may be some NA values in the PCC columns. This would
indicate that one (or both) of the member of that miRNA-mRNA pair had
all-zero counts (i.e. it was unexpressed in all samples)

## 5.2 Merge with 5UTR miRanda results

Read in PCC and miRanda tables

``` r
# Load
Ptuh_miRanda_miRNA_5UTR <- read.table("../output/11.01-Ptuh-mRNA-miRNA-interactions-CDS_5UTR/Ptuh-miRanda-5UTR_1kb-strict-parsed.txt")

# Format the miRNA IDs in miRanda table by removing miRNA coordinates
Ptuh_miRanda_miRNA_5UTR$V1 <- gsub(">", "", Ptuh_miRanda_miRNA_5UTR$V1)
Ptuh_miRanda_miRNA_5UTR$V1 <- sub("\\..*", "", Ptuh_miRanda_miRNA_5UTR$V1)
```

We need to associate the 5UTR genomic coordinates (used in miRanda
output) with gene IDs (used in PCC output)

``` r
# Load and format mapping table
Ptuh_5UTR_FUNids <- read.table("../output/16-Ptuh-annotate-UTRs/Ptuh-5UTR-geneIDs.txt") %>% select(V1, V4)
Ptuh_5UTR_FUNids$V4 <- gsub("Parent=gene-", "", Ptuh_5UTR_FUNids$V4)

# Join with miRanda table to annotate genomic coordinates with gene IDs
Ptuh_miRanda_miRNA_5UTR <- left_join(Ptuh_miRanda_miRNA_5UTR, Ptuh_5UTR_FUNids, by = c("V2" = "V1")) %>% unique()
```

    ## Warning in left_join(Ptuh_miRanda_miRNA_5UTR, Ptuh_5UTR_FUNids, by = c(V2 = "V1")): Detected an unexpected many-to-many relationship between `x` and `y`.
    ## ℹ Row 3 of `x` matches multiple rows in `y`.
    ## ℹ Row 1581 of `y` matches multiple rows in `x`.
    ## ℹ If a many-to-many relationship is expected, set `relationship =
    ##   "many-to-many"` to silence this warning.

Great! Now we can merge the 5UTR miRanda results and PCC values

``` r
# Merge
Ptuh_miRanda_miRNA_5UTR_PCC <- left_join(Ptuh_miRanda_miRNA_5UTR, Ptuh_PCC_miRNA_mRNA, by = c("V1" = "miRNA", "V4.y" = "mRNA")) %>% unique()

# Save
write.csv(Ptuh_miRanda_miRNA_5UTR_PCC, "../output/11.01-Ptuh-mRNA-miRNA-interactions-CDS_5UTR/miRanda_PCC_miRNA_5UTR.csv")
```

Note: there may be some NA values in the PCC columns. This would
indicate that one (or both) of the member of that miRNA-mRNA pair had
all-zero counts (i.e. it was unexpressed in all samples)
