---
title: "18-Ptuh lncRNA matrix "
author: Steven Roberts
date: "`r format(Sys.time(), '%d %B, %Y')`"  
output: 
  html_document:
    theme: readable
    highlight: zenburn
    toc: true
    toc_float: true
    number_sections: true
    code_folding: show
    code_download: true
---

```{r setup, include=FALSE}
library(knitr)
library(tidyverse)
knitr::opts_chunk$set(
  echo = TRUE,         # Display code chunks
  eval = FALSE,         # Evaluate code chunks
  warning = FALSE,     # Hide warnings
  message = FALSE,     # Hide messages
  fig.width = 6,       # Set plot width in inches
  fig.height = 4,      # Set plot height in inches
  fig.align = "center" # Align plots to the center
)
```



```{bash}
head ../output/17-Ptuh-lncRNA/Ptuh-lncRNA.gtf
```

Get BAMS


https://gannet.fish.washington.edu/seashell/bu-github/deep-dive-expression/F-Ptuh/output/06-Ptuh-Hisat/RNA-POC-47.sorted.bam



```{bash}
wget -r -l1 -nd -nc -A ".sorted.bam" -P ../data/18-Ptuh-lncRNA-matrix \
https://gannet.fish.washington.edu/seashell/bu-github/deep-dive-expression/F-Ptuh/output/06-Ptuh-Hisat/
```



```{bash}
#sed -n '261p' ../output/17-Ptuh-lncRNA/Ptuh-lncRNA.gtf
```
```{bash}
#sed -n '261p' ../output/17-Ptuh-lncRNA/lncRNA.gtf
```



```{r, engine='bash'}
/home/shared/subread-2.0.5-Linux-x86_64/bin/featureCounts \
-T 42 \
-a ../output/17-Ptuh-lncRNA/Ptuh-lncRNA.gtf \
-o ../output/18-Ptuh-lncRNA-matrix/Ptuh-lncRNA-counts.txt \
-t lncRNA \
-g gene_id \
-p \
../data/18-Ptuh-lncRNA-matrix/*sorted.bam
```

```{bash}
grep -c '^l' ../output/18-Ptuh-lncRNA-matrix/Ptuh-lncRNA-counts.txt
sort ../output/18-Ptuh-lncRNA-matrix/Ptuh-lncRNA-counts.txt | uniq -d
```
```{bash}
md5sum ../output/18-Ptuh-lncRNA-matrix/Ptuh-lncRNA-counts.txt
```

